#pragma once
#include "lvgl.h"
extern const lv_img_dsc_t art_fighter;
extern const lv_img_dsc_t art_enemy;
extern const lv_img_dsc_t art_cloud;
extern const lv_img_dsc_t art_sun;
extern const lv_img_dsc_t art_moon;
extern const lv_img_dsc_t art_tile_0;
extern const lv_img_dsc_t art_tile_1;
extern const lv_img_dsc_t art_tile_2;
extern const lv_img_dsc_t art_tile_3;
extern const lv_img_dsc_t art_tile_4;
extern const lv_img_dsc_t art_tile_5;
extern const lv_img_dsc_t art_tile_6;
extern const lv_img_dsc_t art_tile_7;
extern const lv_img_dsc_t art_tile_8;
extern const lv_img_dsc_t art_icon_voice;
extern const lv_img_dsc_t art_icon_music;
extern const lv_img_dsc_t art_icon_games;
extern const lv_img_dsc_t art_icon_pictures;
extern const lv_img_dsc_t art_icon_settings;
extern const lv_img_dsc_t art_icon_files;
extern const lv_img_dsc_t art_icon_home;
extern const lv_img_dsc_t art_icon_shooter;
extern const lv_img_dsc_t art_icon_shooter_small;
extern const lv_img_dsc_t art_icon_tiles;
extern const lv_img_dsc_t art_icon_tiles_small;
extern const lv_img_dsc_t art_icon_flood;
extern const lv_img_dsc_t art_icon_flood_small;
